#!/usr/bin/env node

import { promises as fs } from 'fs';
import path from "path";
import childProcess from "child_process";
import { exit } from "process";
const __dirname = import.meta.dirname;

const binaryName = "jstz";

function getBinaryPath() {
  try {
    // Resolving will fail if the optionalDependency was not installed
    return require.resolve(`${binaryName}`);
  } catch (e) {
    return path.join(__dirname, binaryName);
  }
}

try {
  await fs.access(getBinaryPath());
} catch {
  console.log("fail!");
  exit(1);
}

try {
  childProcess.execFileSync(getBinaryPath(), process.argv.slice(2), {
    stdio: "inherit",
  });
} catch (e) {
  if (e.code) {
    exit(1);
  } else {
    exit(e.status);
  }
}
