#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const childProcess = require("child_process");

// Windows binaries end with .exe so we need to special case them.
const binaryName = "jstz";

function getBinaryPath() {
  try {
    // Resolving will fail if the optionalDependency was not installed
    return require.resolve(`${binaryName}`);
  } catch (e) {
    return path.join(__dirname, binaryName);
  }
}

try {
  await fs.access(getBinaryPath());
} catch {
  console.log("fail!");
  process.exit(1);
}

try {
  childProcess.execFileSync(getBinaryPath(), process.argv.slice(2), {
    stdio: "inherit",
  });
} catch (e) {
  if (e.code) {
    process.exit(1);
  } else {
    process.exit(e.status);
  }
}
